"""Throwaway: first-pass curation of the Ragas question set with the Agent SDK.

    uv run --with claude-agent-sdk python -m scripts.curate_questions --dry-run
    uv run --with claude-agent-sdk python -m scripts.curate_questions

Runs on the Claude Code subscription, not an API key: claude-agent-sdk drives
the local `claude` CLI, so there is no ANTHROPIC_API_KEY anywhere here.

Design notes, because two of them are load-bearing:

**One query() per question, no conversation.** Each call is a fresh context.
Chaining 155 judgements into one chat would let question 90's verdict be
coloured by question 12's, and the whole point is an independent read of each.
Cost is the same either way; independence is not.

**The LLM judges, Python selects.** The model never sees the quota. It scores
one question at a time, and `select()` afterwards takes the top 20 per topic.
Asking independent contexts to collectively land on 20-per-topic cannot work,
and asking one context to hold all 155 gives up the independence above.

Output goes through `eval.review.review_question`, which is what the review UI
reads - so every verdict lands in the frontend as a normal keep/drop with a
note, and you can override any of it by hand afterwards. Nothing here is final.
"""
import argparse
import asyncio
import json
import sys
from collections import defaultdict
from pathlib import Path

from eval.review import GENERATED_PATH, load_generated, review_question

JUDGED_PATH = Path(__file__).parent.parent / "eval" / "testset" / "judged.jsonl"
KEEP_PER_TOPIC = 20

SYSTEM = """You curate test questions for a retrieval evaluation over a corpus \
of 100 arXiv machine-learning papers, spanning five topics: retrieval/RAG, \
LLM agents, evaluation/benchmarking, efficient inference/quantization, and \
alignment/RLHF.

The questions were generated by Ragas. Your job is to decide which are fit to \
measure a retrieval system with, and to repair the ones that are nearly there.

HOW TABLES APPEAR IN THIS CORPUS
Some reference chunks are tables. They are not OCR noise. Docling parses each table structurally and its TripletTableSerializer flattens it into "row, column = value" triplets before chunking, so a results table reaches you as prose like "SmoothQuant LLM-QAT, WinoGrande = 74.9 71.6". That is the intended representation, the cell values are intact, and it is exactly what the retrieval system stores and searches over. Apply the same criteria below to these chunks as to any other.

WHAT THE QUESTIONS ARE FOR
Each question ships with the exact corpus chunks it was seeded from. A \
retrieval system is scored on whether it returns those chunks. So a good \
question is one that (a) is genuinely answerable from its reference contexts, \
and (b) actually discriminates between retrieval strategies.

DROP a question when any of these hold:
- It names its own answer. "What is the Elo rating of GPT-3.5?" answered by \
"GPT-3.5 has an Elo of 897" is retrievable on the entity alone, so every \
retrieval configuration scores identically and the question measures nothing.
- It has a floating referent - "these approaches", "the above method", "this \
dataset" - with no antecedent in the question itself. Unanswerable by anyone \
who cannot already see the seed chunk.
- It is about an OCR artifact rather than a claim in a paper: a code listing, \
a garbled table, line numbers, a JSON dump.
- The reference answer is not actually supported by the reference contexts.
- It is so long or so specific that no person would ever type it.

KEEP a question when it is answerable from its contexts, requires real \
retrieval, and - if multi-hop - genuinely needs more than one chunk.

EDITING - READ THIS CAREFULLY
You may repair a question rather than drop it. Three rules bind every edit:

1. PRESERVE THE PERSONA. These questions were deliberately conditioned on \
personas ("As an ML systems engineer...", "As an NLP evaluation researcher..."). \
The persona is a diversity mechanism, not noise: it is what stops the whole set \
reading in one voice. Keep the persona's perspective, vocabulary and framing. \
Do not neutralise a question into generic prose.

2. PRESERVE THE QUERY STYLE, INCLUDING MISSPELLINGS. Roughly a quarter of \
these questions are deliberately misspelled and a quarter deliberately \
ungrammatical - that is a configured axis of the test set, modelling real \
users who type badly. NEVER correct spelling or grammar. A question reading \
"how does retreival augmented generaton work" is doing its job.

3. IF YOU EDIT THE QUESTION, EDIT THE REFERENCE TO MATCH. The reference is the \
gold answer that a judge grades generated answers against. A reworded question \
with a stale gold answer silently marks correct answers wrong. Equally, an \
edit must not change what the question is ABOUT - the reference chunk ids are \
fixed, so changing the subject makes the labels wrong. Edit surface form only.

Prefer keeping unedited. Edit only when a small repair converts a genuinely \
useful question from unusable to usable.

OUTPUT
Reply with one JSON object and nothing else:

{
  "verdict": "keep" | "drop",
  "score": <0-100, how useful this question is for discriminating retrieval>,
  "reason": "<one sentence, concrete>",
  "flags": ["names_own_answer" | "floating_referent" | "ocr_artifact" |
            "unsupported_reference" | "unrealistic_length" | "none"],
  "edited_question": "<only if you edited it, else omit>",
  "edited_reference": "<required if edited_question is present, else omit>"
}

Score is what ranks questions when more survive than the set has room for, so \
spend it: 90+ is an excellent discriminating question, 50 is borderline, below \
30 is unusable."""


def render(q: dict) -> str:
    contexts = "\n\n".join(
        f"--- reference chunk {cid} ---\n{text}"
        for cid, text in zip(q["reference_chunk_ids"], q["reference_contexts"])
    )
    return f"""TOPIC: {q["topics"][0]}
SYNTHESIZER: {q["synthesizer"]}

QUESTION:
{q["question"]}

REFERENCE ANSWER:
{q["reference"]}

REFERENCE CONTEXTS (the chunks retrieval must find):
{contexts}

Judge this question."""


def parse(text: str) -> dict:
    """The model returns JSON; tolerate it being fenced or padded with prose."""
    start, end = text.find("{"), text.rfind("}")
    if start == -1 or end == -1:
        raise ValueError(f"no JSON object in reply: {text[:200]}")
    return json.loads(text[start : end + 1])


async def judge(q: dict, sem: asyncio.Semaphore, lock: asyncio.Lock) -> dict:
    from claude_agent_sdk import ClaudeAgentOptions, query
    from claude_agent_sdk.types import ResultMessage

    options = ClaudeAgentOptions(
        model="opus",
        effort="high",
        # No tools: this is a pure judgement over text handed to it. Leaving
        # the Claude Code preset on would let it wander the repo.
        tools=[],
        system_prompt=SYSTEM,
    )

    async with sem:
        text = None
        async for message in query(prompt=render(q), options=options):
            if isinstance(message, ResultMessage):
                text = message.result

    if text is None:
        raise RuntimeError(f"{q['id']}: no result message")

    verdict = parse(text)
    row = {"id": q["id"], "topic": q["topics"][0], "synthesizer": q["synthesizer"], **verdict}

    # Appended as each finishes, under a lock, so a crash keeps the judgements
    # already paid for. The review.json write happens once at the end.
    async with lock:
        with JUDGED_PATH.open("a") as f:
            f.write(json.dumps(row) + "\n")
        print(f"  {row['id']} {row['topic']:<11} {row['verdict']:<5} "
              f"score={row.get('score', 0):<4} {row.get('reason', '')[:70]}", flush=True)
    return row


def read_judged() -> list[dict]:
    """Every judgement, last verdict per id winning.

    judged.jsonl is append-only so a crash keeps what was paid for, which means
    re-judging a subset leaves two rows for those ids. The later one is the
    current one.
    """
    if not JUDGED_PATH.is_file():
        return []
    latest: dict[str, dict] = {}
    for line in JUDGED_PATH.read_text().splitlines():
        if line.strip():
            row = json.loads(line)
            latest[row["id"]] = row
    return list(latest.values())


def select(judged: list[dict]) -> tuple[dict[str, str], dict[str, int]]:
    """Top `KEEP_PER_TOPIC` per topic among keeps. Python, not the model.

    Balance is the entire reason the test set was regenerated - v1 came out
    7:1 across topics - so the quota is enforced arithmetically rather than
    asked for in a prompt that 155 independent contexts could not coordinate on.
    """
    by_topic: dict[str, list[dict]] = defaultdict(list)
    for row in judged:
        if row["verdict"] == "keep":
            by_topic[row["topic"]].append(row)

    decisions: dict[str, str] = {r["id"]: "drop" for r in judged}
    kept: dict[str, int] = {}
    for topic, rows in by_topic.items():
        rows.sort(key=lambda r: r.get("score", 0), reverse=True)
        for row in rows[:KEEP_PER_TOPIC]:
            decisions[row["id"]] = "keep"
        kept[topic] = min(len(rows), KEEP_PER_TOPIC)
    return decisions, kept


def apply(judged: list[dict], decisions: dict[str, str]) -> None:
    """Write every verdict through the same interface the UI writes through,
    so the frontend shows them as ordinary reviewable decisions."""
    for row in judged:
        note = f"[auto] score={row.get('score', 0)} {row.get('reason', '')}"
        flags = [f for f in row.get("flags", []) if f != "none"]
        if flags:
            note += f" | flags: {', '.join(flags)}"
        review_question(
            row["id"],
            decision=decisions[row["id"]],
            question=row.get("edited_question"),
            reference=row.get("edited_reference"),
            note=note,
        )


async def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--concurrency", type=int, default=8)
    parser.add_argument("--limit", type=int, default=None, help="judge only the first N")
    parser.add_argument("--dry-run", action="store_true", help="judge, but do not write review.json")
    parser.add_argument("--resume", action="store_true", help="skip ids already in judged.jsonl")
    parser.add_argument(
        "--ids-file",
        type=Path,
        default=None,
        help="JSON list of question ids to judge; re-judges them even if already done",
    )
    args = parser.parse_args()

    questions = load_generated()
    if args.ids_file:
        wanted = set(json.loads(args.ids_file.read_text()))
        todo = [q for q in questions if q["id"] in wanted][: args.limit]
        print(f"re-judging {len(todo)} ids from {args.ids_file.name}")
    else:
        done: set[str] = set()
        if args.resume and JUDGED_PATH.is_file():
            done = {r["id"] for r in read_judged()}
            print(f"resuming: {len(done)} already judged")
        todo = [q for q in questions if q["id"] not in done][: args.limit]

    print(f"{len(todo)} questions to judge from {GENERATED_PATH.name} "
          f"(concurrency {args.concurrency}, model opus, effort high)\n")

    sem = asyncio.Semaphore(args.concurrency)
    lock = asyncio.Lock()
    results = await asyncio.gather(
        *(judge(q, sem, lock) for q in todo), return_exceptions=True
    )

    failed = [r for r in results if isinstance(r, Exception)]
    for e in failed:
        print(f"  FAILED: {type(e).__name__}: {e}", file=sys.stderr)

    judged = read_judged()
    decisions, kept = select(judged)

    print(f"\njudged {len(judged)}, {len(failed)} failed")
    print(f"kept per topic (target {KEEP_PER_TOPIC}):")
    for topic in sorted({r["topic"] for r in judged}):
        n = kept.get(topic, 0)
        short = "  <- SHORT, promote borderline ones by hand" if n < KEEP_PER_TOPIC else ""
        print(f"  {topic:<12} {n}{short}")
    edited = sum(1 for r in judged if r.get("edited_question"))
    print(f"total kept: {sum(kept.values())} | edited: {edited}")

    if args.dry_run:
        print(f"\ndry run - review.json untouched. Judgements in {JUDGED_PATH}")
        return 0

    apply(judged, decisions)
    print(f"\nwrote {len(judged)} decisions to review.json - reload the "
          f"Eval Questions page to see them")
    return 1 if failed else 0


if __name__ == "__main__":
    raise SystemExit(asyncio.run(main()))
